In [2]:
import numpy as np
import matplotlib.pyplot as plt
import logging

import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

print(f'Tensorflow version : {tf.__version__}')
print(f'Using GPU: {"no" if len(tf.config.list_physical_devices("GPU")) == 0 else "yes"}.')

logging.getLogger('tensorflow').setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

Tensorflow version : 2.18.0
Using GPU: yes.


## Linear Regression

In [2]:
# Data
X_train = np.array([[1.0], [2.0]])           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]])       #(price in 1000s of dollars)


In [3]:
l1 = Dense(units=1, activation='linear') # only 1 unit, will only manage 1 w / 1 feature
print(l1.get_weights())     # []
a1 = l1(X_train[0].reshape(1, 1))

w, b = l1.get_weights()    # Actual weights
print(f"w = {w}, b={b}")    # initialized as random numbers

[]


I0000 00:00:1763389608.216464    1867 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1131 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


w = [[-0.26853764]], b=[0.]


In [4]:
# manually set weights
set_w = np.array([[200]])
set_b = np.array([100])

# set_weights takes a list of numpy arrays
l1.set_weights([set_w, set_b])
print(l1.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [5]:
a1 = l1(X_train[0].reshape(1, 1));
manual_a1 = np.dot(set_w, X_train[0].reshape(1, 1)) + set_b;

print(a1)
print(manual_a1)
a1 == manual_a1

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


<tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>

In [6]:
# Now that we know the weights are correct:
y_preds_neural = l1(X_train)
y_preds_manual = np.dot(X_train, set_w) + set_b

(y_preds_manual == y_preds_neural).numpy().all()

np.True_

## Logistic Regression

In [7]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

pos = Y_train == 1
neg = Y_train == 0

X_train[pos]

array([3., 4., 5.], dtype=float32)

In [8]:
model = Sequential([
  # Do not use input_dim
  Dense(units=1, activation='sigmoid', input_dim=1, name='L1') # /opt/conda/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.super().__init__(activity_regularizer=activity_regularizer, **kwargs)
])

model.summary()

/opt/conda/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
w, b =  model.get_layer('L1').get_weights()
print(f'w={w}, b={b}')

w=[[1.6822568]], b=[0.]


In [10]:
right_w, right_b = np.array([[2]]), np.array([-4.5])
model.get_layer('L1').set_weights([
  right_w,  # 2D
  right_b   # 1D
])

model.get_layer('L1').get_weights()

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]

In [19]:
a1 = model.predict(X_train[0].reshape(1, 1))

from mlutils import sigmoid

manual = sigmoid(right_w @ X_train[0].reshape(1, 1) + right_b)

if not a1[0][0] == manual[0][0]:
    print(a1[0][0], manual[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
0.010986942 0.01098694263059318
